# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alexanderlake/FPGA/FlappyBird/FlappyBird.srcs/sources_1/ip/BirdROM/BirdROM.xci
# IP: The module: 'BirdROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexanderlake/FPGA/FlappyBird/FlappyBird.gen/sources_1/ip/BirdROM/BirdROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BirdROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/alexanderlake/FPGA/FlappyBird/FlappyBird.srcs/sources_1/ip/BirdROM/BirdROM.xci
# IP: The module: 'BirdROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexanderlake/FPGA/FlappyBird/FlappyBird.gen/sources_1/ip/BirdROM/BirdROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BirdROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
