# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yhszj/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/SettingROM/SettingROM.xci
# IP: The module: 'SettingROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yhszj/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/SettingROM/SettingROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SettingROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/yhszj/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/SettingROM/SettingROM.xci
# IP: The module: 'SettingROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yhszj/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/SettingROM/SettingROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SettingROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
