# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/HealthROM/HealthROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HealthROM || ORIG_REF_NAME==HealthROM} -quiet] -quiet
