# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/alexanderlake/Desktop/FlappyBird/FlappyBird.runs/synth_1/main.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/alexanderlake/Desktop/FlappyBird/FlappyBird.cache/wt [current_project]
set_property parent.project_path /home/alexanderlake/Desktop/FlappyBird/FlappyBird.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/alexanderlake/Desktop/FlappyBird/FlappyBird.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/BackgroundROM/BackgroundROM.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/BirdROM/BirdROM.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/PipeROM/PipeROM.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/LogoROM/Logo.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/NumberROM/NumberROM.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/ScoreboardROM/ScoreboardROM.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/ScoreNumberROM/ScoreNumberROM.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/SpeedUpROM/SpeedUpROM.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/SettingROM/SettingROM.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/HealthROM/HealthROM.coe
add_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/BackgroundROMNight/BackgroundROMNight.coe
read_verilog -library xil_defaultlib {
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/BackgroundRenderer.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/Ball.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/Bonus.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/BonusRenderer.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/ControlMux.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/DataGenerator.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/DeBounce.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/Decoder.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/Display32Bit.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/InputProcessor.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/LayerMixer.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/Logic.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/MEMS.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/OverlayRenderer.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/Pipe.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/PipeRenderer.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/Profile.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/Score.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/VGADisplay.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/bgm.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/clkdiv.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/clkrim.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/data_processing.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/jump.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/soundeffect.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/uart_rx.v
  /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/new/main.v
}
read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/HealthROM/HealthROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/HealthROM/HealthROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/BirdROM/BirdROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/BirdROM/BirdROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/LogoROM/LogoROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/LogoROM/LogoROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/BackgroundROM/BackgroundROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/BackgroundROM/BackgroundROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/PipeROM/PipeROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/PipeROM/PipeROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/NumberROM/NumberROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/NumberROM/NumberROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/ScoreNumberROM/ScoreNumberROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/ScoreNumberROM/ScoreNumberROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/SpeedUpROM/SpeedUpROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/SpeedUpROM/SpeedUpROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/SettingROM/SettingROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/SettingROM/SettingROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/ScoreboardROM/ScoreboardROM.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/ScoreboardROM/ScoreboardROM_ooc.xdc]

read_ip -quiet /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/BackgroundROMNight/BackgroundROMNight.xci
set_property used_in_implementation false [get_files -all /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/BackgroundROMNight/BackgroundROMNight_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top main -part xc7a35tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
