# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/86187/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/PipeROM/PipeROM.xci
# IP: The module: 'PipeROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86187/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/PipeROM/PipeROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PipeROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/86187/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/PipeROM/PipeROM.xci
# IP: The module: 'PipeROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86187/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/PipeROM/PipeROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PipeROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
