set_property PACKAGE_PIN P17 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
create_clock -period 10 [get_ports Clk]

set_property PACKAGE_PIN B7 [get_ports R[3]]
set_property PACKAGE_PIN C5 [get_ports R[2]]
set_property PACKAGE_PIN C6 [get_ports R[1]]
set_property PACKAGE_PIN F5 [get_ports R[0]]
set_property IOSTANDARD LVCMOS33 [get_ports R[3]]
set_property IOSTANDARD LVCMOS33 [get_ports R[2]]
set_property IOSTANDARD LVCMOS33 [get_ports R[1]]
set_property IOSTANDARD LVCMOS33 [get_ports R[0]]

set_property PACKAGE_PIN D8 [get_ports G[3]]
set_property PACKAGE_PIN A5 [get_ports G[2]]
set_property PACKAGE_PIN A6 [get_ports G[1]]
set_property PACKAGE_PIN B6 [get_ports G[0]]
set_property IOSTANDARD LVCMOS33 [get_ports G[3]]
set_property IOSTANDARD LVCMOS33 [get_ports G[2]]
set_property IOSTANDARD LVCMOS33 [get_ports G[1]]
set_property IOSTANDARD LVCMOS33 [get_ports G[0]]

set_property PACKAGE_PIN E7 [get_ports B[3]]
set_property PACKAGE_PIN E5 [get_ports B[2]]
set_property PACKAGE_PIN E6 [get_ports B[1]]
set_property PACKAGE_PIN C7 [get_ports B[0]]
set_property IOSTANDARD LVCMOS33 [get_ports B[3]]
set_property IOSTANDARD LVCMOS33 [get_ports B[2]]
set_property IOSTANDARD LVCMOS33 [get_ports B[1]]
set_property IOSTANDARD LVCMOS33 [get_ports B[0]]

set_property PACKAGE_PIN D7 [get_ports HSync]
set_property IOSTANDARD LVCMOS33 [get_ports HSync]

set_property PACKAGE_PIN C4 [get_ports VSync]
set_property IOSTANDARD LVCMOS33 [get_ports VSync]

set_property PACKAGE_PIN U4 [get_ports OriginalButtonUp]
set_property IOSTANDARD LVCMOS33 [get_ports OriginalButtonUp]

set_property PACKAGE_PIN R17 [get_ports OriginalButtonDown]
set_property IOSTANDARD LVCMOS33 [get_ports OriginalButtonDown]

set_property PACKAGE_PIN V1 [get_ports OriginalButtonLeft]
set_property IOSTANDARD LVCMOS33 [get_ports OriginalButtonLeft]

set_property PACKAGE_PIN R11 [get_ports OriginalButtonRight]
set_property IOSTANDARD LVCMOS33 [get_ports OriginalButtonRight]

set_property PACKAGE_PIN R15 [get_ports OriginalButtonCentral]
set_property IOSTANDARD LVCMOS33 [get_ports OriginalButtonCentral]

set_property PACKAGE_PIN G2 [get_ports ChipSelect[7]]
set_property PACKAGE_PIN C2 [get_ports ChipSelect[6]]
set_property PACKAGE_PIN C1 [get_ports ChipSelect[5]]
set_property PACKAGE_PIN H1 [get_ports ChipSelect[4]]
set_property PACKAGE_PIN G1 [get_ports ChipSelect[3]]
set_property PACKAGE_PIN F1 [get_ports ChipSelect[2]]
set_property PACKAGE_PIN E1 [get_ports ChipSelect[1]]
set_property PACKAGE_PIN G6 [get_ports ChipSelect[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ChipSelect[7]]
set_property IOSTANDARD LVCMOS33 [get_ports ChipSelect[6]]
set_property IOSTANDARD LVCMOS33 [get_ports ChipSelect[5]]
set_property IOSTANDARD LVCMOS33 [get_ports ChipSelect[4]]
set_property IOSTANDARD LVCMOS33 [get_ports ChipSelect[3]]
set_property IOSTANDARD LVCMOS33 [get_ports ChipSelect[2]]
set_property IOSTANDARD LVCMOS33 [get_ports ChipSelect[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ChipSelect[0]]

set_property PACKAGE_PIN D4 [get_ports SegmentSelectRight[7]]
set_property PACKAGE_PIN E3 [get_ports SegmentSelectRight[6]]
set_property PACKAGE_PIN D3 [get_ports SegmentSelectRight[5]]
set_property PACKAGE_PIN F4 [get_ports SegmentSelectRight[4]]
set_property PACKAGE_PIN F3 [get_ports SegmentSelectRight[3]]
set_property PACKAGE_PIN E2 [get_ports SegmentSelectRight[2]]
set_property PACKAGE_PIN D2 [get_ports SegmentSelectRight[1]]
set_property PACKAGE_PIN H2 [get_ports SegmentSelectRight[0]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectRight[7]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectRight[6]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectRight[5]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectRight[4]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectRight[3]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectRight[2]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectRight[1]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectRight[0]]

set_property PACKAGE_PIN B4 [get_ports SegmentSelectLeft[7]]
set_property PACKAGE_PIN A4 [get_ports SegmentSelectLeft[6]]
set_property PACKAGE_PIN A3 [get_ports SegmentSelectLeft[5]]
set_property PACKAGE_PIN B1 [get_ports SegmentSelectLeft[4]]
set_property PACKAGE_PIN A1 [get_ports SegmentSelectLeft[3]]
set_property PACKAGE_PIN B3 [get_ports SegmentSelectLeft[2]]
set_property PACKAGE_PIN B2 [get_ports SegmentSelectLeft[1]]
set_property PACKAGE_PIN D5 [get_ports SegmentSelectLeft[0]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectLeft[7]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectLeft[6]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectLeft[5]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectLeft[4]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectLeft[3]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectLeft[2]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectLeft[1]]
set_property IOSTANDARD LVCMOS33 [get_ports SegmentSelectLeft[0]]

set_property PACKAGE_PIN K13 [get_ports RxUART]
set_property IOSTANDARD LVCMOS33 [get_ports RxUART]

set_property PACKAGE_PIN F6 [get_ports DataOutLED[7]]
set_property PACKAGE_PIN G4 [get_ports DataOutLED[6]]
set_property PACKAGE_PIN G3 [get_ports DataOutLED[5]]
set_property PACKAGE_PIN J4 [get_ports DataOutLED[4]]
set_property PACKAGE_PIN H4 [get_ports DataOutLED[3]]
set_property PACKAGE_PIN J3 [get_ports DataOutLED[2]]
set_property PACKAGE_PIN J2 [get_ports DataOutLED[1]]
set_property PACKAGE_PIN K2 [get_ports DataOutLED[0]]
set_property IOSTANDARD LVCMOS33 [get_ports DataOutLED[7]]
set_property IOSTANDARD LVCMOS33 [get_ports DataOutLED[6]]
set_property IOSTANDARD LVCMOS33 [get_ports DataOutLED[5]]
set_property IOSTANDARD LVCMOS33 [get_ports DataOutLED[4]]
set_property IOSTANDARD LVCMOS33 [get_ports DataOutLED[3]]
set_property IOSTANDARD LVCMOS33 [get_ports DataOutLED[2]]
set_property IOSTANDARD LVCMOS33 [get_ports DataOutLED[1]]
set_property IOSTANDARD LVCMOS33 [get_ports DataOutLED[0]]

set_property PACKAGE_PIN T1 [get_ports beep]
set_property IOSTANDARD LVCMOS33 [get_ports beep]

set_property IOSTANDARD LVCMOS33 [get_ports sd]
set_property PACKAGE_PIN M6 [get_ports sd]

set_property IOSTANDARD LVCMOS33 [get_ports SD]
set_property PACKAGE_PIN R1 [get_ports SD]