# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/NumberROM/NumberROM.xci
# IP: The module: 'NumberROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/NumberROM/NumberROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NumberROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/alexanderlake/Desktop/FlappyBird/FlappyBird.srcs/sources_1/ip/NumberROM/NumberROM.xci
# IP: The module: 'NumberROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexanderlake/Desktop/FlappyBird/FlappyBird.gen/sources_1/ip/NumberROM/NumberROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NumberROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
